#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
  namespace: default
  labels:
    app: netflix-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix-app
      tier: frontend
      version: 1.0.0
      #pod tempalte
  template:
    metadata:
      labels:
        app: netflix-app
        tier: frontend
        version: 1.0.0
    spec: # Pod spec
      containers:
      - name: netflix-container
        image: 720826398753.dkr.ecr.us-east-1.amazonaws.com/netflix-app-ecr:v1.0
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app-service
  labels:
    app: netflix-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netflix-app
