# Default values for netflix-clone-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ns: netflix-prod
replicaCount: 3 #number of pod replicas to run
appName: neftlix-clone

image:
  repo: 720826398753.dkr.ecr.us-east-1.amazonaws.com/netflix-app-ecr
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
